### ISSUE TITLE
How to save full results in txt

### ISSUE THREAD

**Issue by DharmX1** [aztecrabbit/bugscanner-go#10]
How can I save the full results I get from scanning subdomain list. It only saves results which use cloudflare sever to output file . As I'm using termux.
I normally use following command:-
bugscanner-go scan direct -f subdomain.txt -o scanned.txt

**Comment by aztecrabbit** [comment]
output is saved only when success, if you want full output, just use `bugscanner-go scan direct -f subdomain.txt > output.txt`, but the log file will be verbose
