### ISSUE TITLE
How to change the payload?

### ISSUE THREAD

**Issue by talesam** [aztecrabbit/bugscanner-go#8]
There is a default payload using HEAD, how do I change it, for example, use GET or PUT or change the whole payload format?

**Comment by MC189** [comment]
Hi @talesam, you can check the available parameter through `-h`.
- Method: `-m GET`
- Payload: `--payloads "GET / HTTP/1.1\r\n\r\n`
- Help: `bugscannger-go -h`, `bugscanner-go scan -h`, `bugscanner-go scan cdn-ssl -h`, etc.
